# Generated by Django 3.2.16 on 2022-10-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_lyrics_lyric'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='song',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artiste',
        ),
    ]
