# Generated by Django 3.2.16 on 2022-10-25 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20221024_2307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song',
            new_name='song_id',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste',
            new_name='artiste_id',
        ),
    ]
