# Generated by Django 3.2.16 on 2022-10-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_auto_20221025_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='song_parent',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artiste_id',
            new_name='artiste_parent',
        ),
    ]
