# Generated by Django 3.2.16 on 2022-10-25 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_auto_20221025_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyric',
            name='song_parent',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artiste_parent',
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artiste_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
    ]
