# Generated by Django 3.2.16 on 2022-10-27 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_auto_20221025_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
